namespace: default

gitlab:
  rootPassword:
  host:
  email:
    address: "gitlab@rhdemo.com"
    displayName: "Gitlab"

rhdh:
  template:
    group: rhdh
    templates:
      - project: opencodequest-templates
        branch: main
        templates:
          - scaffolder-templates/quarkus-ai/template.yaml
          - scaffolder-templates/quarkus-postgresql/template.yaml
          - scaffolder-templates/quarkus-with-spring-postgresql/template.yaml
          - scaffolder-templates/fight-ui/template.yaml

backstage:
  host:

keycloak:
  host:
  realm:
  loginRealm:
  clientId:
  clientSecret:

gitops:
  host:

kubernetes:
  api: https://kubernetes.default.svc

oauth2:
  issuer:

cluster:
  subdomain:

quay:
  project: quayadmin

stackrox:
  endpoint: central.stackrox.svc.cluster.local:443

orchestrator:
  sonataFlowDataIndexService:

argocd:
  enabled: true
  syncwave: "3"
