namespace: default

gitlab:
  rootPassword:
  host:
  email:
    address: "gitlab@rhdemo.com"
    displayName: "Gitlab"

rhdh:
  template:
    group: rhdh
    templates:
      - project: developer-hub-config
        branch: main
        templates:
          - values.yaml
      - project: opencodequest-templates
        branch: main
        templates:
          - scaffolder-templates/quarkus-ai/template.yaml
          - scaffolder-templates/quarkus-postgresql/template.yaml
          - scaffolder-templates/quarkus-with-spring-postgresql/template.yaml
          - scaffolder-templates/fight-ui/template.yaml

backstage:
  host:

keycloak:
  host:
  realm:
  loginRealm:
  clientId:
  clientSecret:

gitops:
  host:

kubernetes:
  api: https://kubernetes.default.svc

oauth2:
  issuer:

cluster:
  subdomain:

orchestrator:
  sonataFlowDataIndexService:

argocd:
  enabled: true
  syncwave: "-2"
