gitops:
  namespace: openshift-gitops

application:
  name: rhdh
  destination:
    namespace: rhdh

helm:
  repoURL: https://github.com/rh-idp-lab/helm.git
  targetRevision: main
  path: redhat-developer-hub
  inlineValues: {}  # override with cluster-specific values at deploy time
