---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.gitops.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    namespace: {{ .Values.application.destination.namespace }}
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 15
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: {{ .Values.helm.repoURL }}
    targetRevision: {{ .Values.helm.targetRevision }}
    path: {{ .Values.helm.path }}
    helm:
      values: |
        {{- .Values.helm.inlineValues | toYaml | nindent 8 }}
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: backstage-developer-hub
      jsonPointers:
        - /spec/strategy
