apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecretsConfig
metadata:
  name: cluster
  namespace: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  controllerConfig:
    networkPolicies:
      - name: allow-vault-egress
        componentName: CoreController
        egress:
          - ports:
              - port: {{ .Values.vault.port | default 8200 }}
                protocol: TCP
