apiVersion: v2
name: external-secrets
description: Red Hat External Secrets Operator (OLM) + Vault ClusterSecretStore
type: application
version: 0.2.0

dependencies:
  - name: vault-integration
    version: 0.1.0
    repository: file://vault-integration
