operator:
  channel: stable-v1
  startingCSV: openshift-external-secrets-operator.v1.1.0
  installPlanApproval: Automatic

vault-integration:
  vault:
    namespace: vault
    name: vault
    auth:
      namespace: default
