kind: ConfigMap
apiVersion: v1
metadata:
  name: rbac-conditional-policies
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "redhat-developer-hub-prereqs.labels" . | nindent 4 }}
  annotations:
    {{- include "redhat-developer-hub-prereqs.argocd-syncwave" . | nindent 4 }}
data:
  rbac-conditional-policies.yaml: |
    {{- toYaml .Values.rbacConditionalPolicies | nindent 4 }}
