{{- $ns := .Values.namespace -}}
{{- $existing := lookup "v1" "Secret" $ns "backstage-backend" -}}
{{- $backendSecret := "" -}}
{{- if $existing -}}
{{- $backendSecret = index $existing.data "BACKEND_SECRET" | b64dec -}}
{{- else -}}
{{- $backendSecret = randAlphaNum 24 -}}
{{- end -}}
kind: Secret
apiVersion: v1
metadata:
  name: backstage-backend
  namespace: {{ $ns }}
  annotations:
    {{- include "redhat-developer-hub-prereqs.argocd-syncwave" . | nindent 4 }}
stringData:
  BACKEND_SECRET: {{ $backendSecret }}
type: Opaque
