namespace: rhdh

backstage:
  name: developer-hub
  host:

cluster:
  subdomain:

gitlab:
  host:

keycloak:
  host:
  realm: sso
  loginRealm: ""

gitops:
  host:

quay:
  project: quayadmin

argocd:
  enabled: true
  syncwave: "2"
